version: '3'
services:
  unified:
    build: 
      context: docker_unified #公式gitのdockerfile　ビルドに時間がかかる
    volumes:
      - ./dataset:/dataset
    tty: true
    deploy: # MVSでCUDAを使用すると速くなる
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]